# Generated by Django 2.0.4 on 2018-04-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(max_length=200),
        ),
    ]
